config/routes.rb
Rails.application.routes.draw do
  
  root to: 'cctv#home'
  get 'cctv/contact'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	
 	resources :customers , only: [:new, :create, :update, :show, :edit]
 	get '/customers', to: 'customers#new'
 	
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cctv.rb
class Cctv < ApplicationRecord
	belongs_to :product
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  
  has_many :items, dependent: :destroy, inverse_of: :customer
  has_many :dome_cameras, ->{ where(product_name: "DOME CAMERA") }, :class_name => "Item", dependent: :destroy, inverse_of: :customer
  has_many :bullet_cameras, ->{ where(product_name: "BULLET CAMERA") }, class_name: "Item", dependent: :destroy, inverse_of: :customer
  has_many :dvrs, ->{ where(product_name: "DVR") }, class_name: "Item", dependent: :destroy, inverse_of: :customer
  has_many :smpss, ->{ where(product_name: "SMPS") }, class_name: "Item", dependent: :destroy, inverse_of: :customer
  has_many :connectors, ->{ where(product_name: "CONNECTOR") }, class_name: "Item", dependent: :destroy, inverse_of: :customer
  has_many :hdds, ->{ where(product_name: "HDD") }, class_name: "Item", dependent: :destroy, inverse_of: :customer
  has_many :wires, ->{ where(product_name: "WIRE") }, class_name: "Item", dependent: :destroy, inverse_of: :customer
  has_many :installations, ->{ where(product_name: "INSTALLATION") }, class_name: "Item", dependent: :destroy, inverse_of: :customer
 

  accepts_nested_attributes_for :items, allow_destroy: true
  accepts_nested_attributes_for :dome_cameras, allow_destroy: true
  accepts_nested_attributes_for :bullet_cameras, allow_destroy: true
  accepts_nested_attributes_for :dvrs, allow_destroy: true
  accepts_nested_attributes_for :smpss, allow_destroy: true
  accepts_nested_attributes_for :connectors, allow_destroy: true
  accepts_nested_attributes_for :hdds, allow_destroy: true
  accepts_nested_attributes_for :wires, allow_destroy: true
  accepts_nested_attributes_for :installations, allow_destroy: true

  # validates_associated :items
  


  validates :name, presence: true
  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/ 
  validates_length_of :contact, is: 10
  validates :address, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
	belongs_to :cctv
	belongs_to :customer, inverse_of: :items
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :cctvs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cctv_controller.rb
class CctvController < ApplicationController
  def home
  end

  def contact
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update]

  def show
    @customer = Customer.find(params[:id])
    @items = @customer.items.all
  end

  def new
    @customer = Customer.new
    @customer.dome_cameras.new
    @customer.bullet_cameras.new
    @customer.dvrs.new
    @customer.smpss.new
    @customer.connectors.new
    @customer.hdds.new
    @customer.wires.new
    @customer.installations.new
  end
  
  def edit
   
  end

  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        CustomerMailer.send_welcome_mail(@customer).deliver!
        format.html { redirect_to @customer, notice: 'YOUR REQUEST IS CONFIRMED...!' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # def destroy
  #   @customer.destroy
  #   respond_to do |format|
  #     format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
  
      # params.require(:customer).permit(:id, :name, :contact, :email, :address, items_attributes: Item.attribute_names.map(&:to_sym).push(:_destroy))
      params.require(:customer).permit(:id, :name, :contact, :email, :address, :dome_cameras_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity], :bullet_cameras_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity], :dvrs_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity],:smpss_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity], :connectors_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity], :hdds_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity], :wires_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity], :installations_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity])
      # params.require(:customer).permit(:name, :contact, :email, :address, :dome_cameras_attributes => [:id, :_destroy, :product_name, :customer_id, :cctv_id, :price, :quantity])
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cctv_helper.rb
module CctvHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/cctv/contact.html.erb
<div class="porta_tm_home_title_wrap">
	<div class="inner">
		<div class="logo">
			<center>
				<%= link_to image_tag("logo.png"), root_path %>
			</center>
		</div>
	</div>
</div>
		
<div class="contact_page">
<center>			
	<h6><i class="fa fa-address-card-o"></i>Address:</h6>
	<h5>F-82, 1st Floor, Raiser Plaza, Jaipur (RAJ.)</h5>			
	</br>
	<h6><i class="fa fa-phone"></i>Phone:</h6>
	<h5>+91-9799974142</h5>	
	</br>
	<h6><i class="fa fa-at"></i>Email</h6>
	<h5>st@smarttechno.com</h5>			
</center>
</div>
<footer class="fixed-bottom">
	<div class="container">
		<center class="copyright">
			<label class="wow fadeIn" style="color:white" data-wow-duration="1.2s">Copyright</label>
				<p class="wow fadeIn" data-wow-duration="1.2s" data-wow-delay="0.4s">&copy; 2018. All rights are reserved.</p>
		</center>
	</div>	
</footer>

app/views/cctv/home.html.erb
<!-- WRAPPER ALL -->
<div class="porta_tm_wrapper_all">
<!-- CONTENT -->
	<div class="porta_tm_content">
		<div class="container">
			<div class="porta_tm_home_title_wrap index">			
				<div class="inner">
					<h3>
						<div class="logo">
							<center>
				            <%= link_to image_tag("logo.png"), root_path %>
			                </center>
						</div>
	            		<center class="animated">
							<span>Where Do You Want To Install Cameras ?</span>
						</center>
					</h3>
				</div>
			</div>
		</div>
		<div class="porta_tm_section">
			<div class="container">
				<div class="porta_tm_news_wrap">
					<ul>
						
						<li class="wow slideInUp" data-wow-duration="0.3s" style="visibility: visible; animation-duration: 0.3s; animation-name: slideInUp;">
							<div class="inner">
								<div class="definitions_wrap">
									</br>
									<div class="title">
										<h3>HOME</h3>
									</div>
									<div class="image">
										<center><a class="dark_logo">
										    <%= link_to image_tag("house.png"), new_customer_path %></a>
										</center>
									</div>
							        <div class="read_more">
										<%= link_to "MORE", new_customer_path %>
									</div>
								</div>
							</div>
						</li>
						
						<li class="wow slideInUp" data-wow-duration="0.6s" style="visibility: visible; animation-duration: 0.6s; animation-name: slideInUp;">
							<div class="inner">
								<div class="definitions_wrap">
									</br>
									<div class="title">
										<h3>OFFICE</h3>
									</div>
									<div class="image">
									    <center><a class="dark_logo">
										    <%= link_to image_tag("3d-building.png"), new_customer_path %></a>
										</center>
									</div>
									<div class="read_more">
										<%= link_to "MORE.",new_customer_path %>
									</div>
								</div>
							</div>
						</li>
						
						<li class="wow slideInUp" data-wow-duration="0.9s" style="visibility: visible; animation-duration: 0.9s; animation-name: slideInUp;">
					        <div class="inner">
								<div class="definitions_wrap">
									</br>
									<div class="title">
										<h3>OTHER</h3>
									</div>
									<div class="image">
									<center><a class="dark_logo">
										    <%= link_to image_tag("icon.png"), new_customer_path %></a>
										</center>
									</div>
									<div class="read_more">
										<%= link_to "MORE.",new_customer_path %>
									</div>
								</div>
							</div>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<center class="copyright">
			<%= link_to "CONTACT US:", cctv_contact_path %></br>
				<label class="wow fadeIn" style="color:white" data-wow-duration="1.2s">Copyright</label>
				<p class="wow fadeIn" data-wow-duration="1.2s" data-wow-delay="0.4s">&copy; 2018. All rights are reserved.</p>
		</center>
	</div>
</div>

app/views/customers/_customer.html.erb
  <div id= "spinner">
    <%= image_tag('giphy.gif') %>  
  </div>
   
  <div class="form-group col-md-6 name">
    <label>NAME</label>
    <%= f.text_field :name, label: false, onkeyup: "forUpperCase()", class: "form-control customer-details", :placeholder => "Name", id: "customer-name" %>
  </div>


  <div class="form-group col-md-6 ">
    <label>CONTACT</label><small class="alertInfo pull-right"></small>
    <%= f.number_field :contact, title: "Please Enter Valid Number", label: false, class: "form-control customer-details", id: "customer-contact", :placeholder => "Contact" %>
  </div>

  <div class="form-group">
    <label>EMAIL</label>
    <%= f.email_field :email, title: "Please Enter Valid Email Address", label: false, class: "form-control customer-details", id: "customer-email", :placeholder => "Email" %>
  </div>

  <div class="form-group">
    <label>ADDRESS</label>
    <%= f.text_field :address, label: false, class: "form-control customer-details",id: "customer-address", :placeholder => "address" %>
  </div>


  <%= f.submit "REQUEST", class: "btn btn-default request", onclick: "validate()" %>
 

app/views/customers/_customerPrint.html.erb
<div class="table-responsive">
  <table class="table">
    <tr>
      <td><strong>NAME :</strong></td>
      <td><%= @customer.name %></td>
    </tr>
    <tr>
      <td><strong>CONTACT :</strong></td>
      <td><%= @customer.contact %></td>
    </tr>
    <tr>
      <td><strong>EMAIL :</strong></td>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <td><strong>ADDRESS :</strong></td>
      <td><%= @customer.address %></td>
    </tr>
  </table>
</div>
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>ITEMS NAME</th>
        <th>CATEGORY</th>
        <th>PRICE</th>
        <th>QUANTITY</th>
        <th>TOTAL</th>
      </tr>
    </thead>
    <tbody> 
      <% grandTotal = 0 %>
      <% @items.each do |item| %> 
        <tr>  
          <td><%= item.product_name %></td>
          <td ><%= item.cctv.category %></td>
          <td style="width:150px;text-align: right;"><i class="fa fa-inr">&nbsp</i><%= item.price %></td>
          <td style="width:80px;text-align: center;"><%= item.quantity %></td>
          <% total = item.price.to_i * item.quantity.to_i %>
          <td style="width:220px;text-align: right;"><i class="fa fa-inr">&nbsp</i><%= total %>.00</td>
        </tr>
        <% grandTotal += total %>
      <% end %>
      <tr>
        <td colspan="4"></td>
        <td style="text-align: right;">GRAND TOTAL: <i class="fa fa-inr">&nbsp</i><%= grandTotal %>.00</td>
      </tr>
    </tbody>
  </table>
</div>

app/views/customers/_form.html.erb
<%= form_for @customer, remote: true do |f| %>
	
  <div class="logo">
		<center><%= link_to image_tag("logo.png"), root_path %></a></center>
	</div>
   	<div class="table-responsive" style="margin-bottom: 2%;">
   		<table class="table-for-mobile">
  			<tr>
    				<td><strong>DOME CAMERA:</strong><input type="number" class="form-control initialQty" id="dome" placeholder="  QUANTITY..." ></td>
    				<td><strong>BULLET CAMERA:</strong><input type="number" class="form-control initialQty" id="bullet" placeholder="  QUANTITY..." ></td>
    				<td style="width: 47%;"><strong>TOTAL CAMERA:  </strong><br><span id="totalqty">0</span></td>
  			</tr>
			</table>
		</div>
		<%= render 'item', f: f %></br>
		<center>
			<a class="btn btn-primary proceed" data-toggle="modal" data-target="#customer-model" id="customerModel" ><i class="fa fa-hand-o-up"></i> PROCEED</a>
		</center>

		<div class="modal fade" id="customer-model" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
	    
	    <div class="modal-dialog modal-md" id= "customermm">
	      	
	      	<div class="modal-content">
	        	
	        	<div class="container-fluid invoice_wrapper">
	          		<%= render 'customer', f: f %> 
	        	</div>
	      	
	      	</div>
	    
	    </div>
	
	</div>
	
<% end %>

app/views/customers/_item.html.erb
<div class="table-responsive">
<table class="table-for-mobile">
	<thead>
		<tr>
			<th class="center item-header">ITEM</th>
			<th class="center category-header">CATEGORY</th>
			<th class="center price-header">PRICE</th>
			<th class="center qty-header">QTY</th>
			<th class="center total-header">TOTAL</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<%= f.fields_for :dome_cameras do |dome| %>
				<td><%= dome.text_field :product_name, :value => "DOME CAMERA", :readonly => true, class: "1 form-control product-name" %></td>
				<td><%= dome.collection_select :cctv_id, Cctv.all, :id, :category, { include_blank: "select category"}, {class: "11 category-dropdown form-control", id: "dome-category"} %></td>
				<td><%= dome.number_field :price, :readonly => true, class: "form-control price dome-camera-price" %></td>
				<td><%= dome.number_field :quantity, :readonly => true, :value => 1, class: "form-control qty", id: "dome-qty" %></td>
				<td><i class="fa fa-inr"></i><span class="total pull-right">0</span></td>
				<%= dome.hidden_field :customer_id %>
			<% end %>
		</tr>
		
		<tr>
			<%= f.fields_for :bullet_cameras do |bullet| %>
				<td><%= bullet.text_field :product_name, :value => "BULLET CAMERA", :readonly => true, class: "2 form-control product-name" %></td>
				<td><%= bullet.collection_select :cctv_id, Cctv.all, :id, :category, { include_blank: "select category"}, {class: "12 category-dropdown form-control"} %></td>
				<td><%= bullet.number_field :price, :readonly => true, class: "form-control price bullet-camera-price" %></td>
				<td><%= bullet.number_field :quantity, :readonly => true, :value => 1, class: "form-control qty", id: "bullet-qty" %></td>
				<td><i class="fa fa-inr"></i><span class="total pull-right">0</span></td>
				<%= bullet.hidden_field :customer_id %>
			<% end %>
		</tr>
		
		<tr>
			<%= f.fields_for :dvrs do |dvr| %>
				<td><%= dvr.text_field :product_name, :value => "DVR", :readonly => true, class: "3 form-control product-name" %></td>
				<td><%= dvr.collection_select :cctv_id, Cctv.all, :id, :category, { include_blank: "select category"}, {class: "13 category-dropdown dvr form-control"} %></td>
				<td><%= dvr.number_field :price, :readonly => true, class: "form-control price" %></td>
				<td><%= dvr.number_field :quantity, :readonly => true, :value => 1, class: "form-control qty" %></td>
				<td><i class="fa fa-inr"></i><span class="total pull-right">0</span></td>
				<%= dvr.hidden_field :customer_id %>
			<% end %>
		</tr>
		
		<tr>
			<%= f.fields_for :smpss do |smps| %>
				<td><%= smps.text_field :product_name, :value => "SMPS", :readonly => true, class: "4 form-control	product-name" %></td>
				<td><%= smps.collection_select :cctv_id, Cctv.all, :id, :category, { include_blank: "select category"}, {class: "14 category-dropdown smps form-control"} %></td>
				<td><%= smps.number_field :price, :readonly => true, class: "form-control price" %></td>
				<td><%= smps.number_field :quantity, :readonly => true, :value => 1, class: "form-control qty" %></td>
				<td><i class="fa fa-inr"></i><span class="total pull-right">0</span></td>
				<%= smps.hidden_field :customer_id %>
			<% end %>
		</tr>
		
		<tr>
			<%= f.fields_for :connectors do |connector| %>
				<td><%= connector.text_field :product_name, :value => "CONNECTOR", :readonly => true, class: "5 form-control product-name" %></td>
				<td><%= connector.collection_select :cctv_id, Cctv.all, :id, :category, { include_blank: "select category"}, {class: "15 category-dropdown connector form-control"} %></td>
				<td><%= connector.number_field :price, :readonly => true, class: "form-control price" %></td>
				<td><%= connector.number_field :quantity, :readonly => true, :value => 1, class: "form-control connector-qty qty" %></td>
				<td><i class="fa fa-inr"></i><span class="total pull-right">0</span></td>
				<%= connector.hidden_field :customer_id %>
			<% end %>
		</tr>
		
		<tr>
			<%= f.fields_for :hdds do |hdd| %>
				<td><%= hdd.text_field :product_name, :value => "HDD", :readonly => true, class: "6 form-control product-name" %></td>
				<td><%= hdd.collection_select :cctv_id, Cctv.all, :id, :category, { include_blank: "select category"}, {class: "16 category-dropdown form-control"} %></td>
				<td><%= hdd.number_field :price, :readonly => true, class: "form-control price" %></td>
				<td><%= hdd.number_field :quantity, :readonly => true, :value => 1, class: "form-control qty" %></td>
				<td><i class="fa fa-inr"></i><span class="total pull-right">0</span></td>
				<%= hdd.hidden_field :customer_id %>
			<% end %>
		</tr>
		
		<tr>
			<%= f.fields_for :wires do |wire| %>
				<td><%= wire.text_field :product_name, :value => "WIRE", :readonly => true, class: "7 form-control product-name" %></td>
				<td><%= wire.collection_select :cctv_id, Cctv.all, :id, :category, { include_blank: "select category"}, {class: "17 category-dropdown form-control"} %></td>
				<td><%= wire.number_field :price, :readonly => true, class: "form-control price" %></td>
				<td><%= wire.number_field :quantity, :readonly => true, :value => 1, class: "form-control qty" %></td>
				<td><i class="fa fa-inr"></i><span class="total pull-right">0</span></td>
				<%= wire.hidden_field :customer_id %>
			<% end %>
		</tr>
		
		<tr>
			<%= f.fields_for :installations do |installation| %>
				<td><%= installation.text_field :product_name, :value => "INSTALLATION", :readonly => true, class: "8 form-control product-name" %></td>
				<td><%= installation.collection_select :cctv_id, Cctv.all, :id, :category, { include_blank: "select category"}, {class: "18 category-dropdown form-control"} %></td>
				<td><%= installation.number_field :price, :readonly => true, class: "form-control price" %></td>
				<td><%= installation.number_field :quantity, :readonly => true, :value => 1, class: "form-control qty" %></td>
				<td><i class="fa fa-inr"></i><span class="total pull-right">0</span></td>
				<%= installation.hidden_field :customer_id %>
			<% end %>
		</tr>
		
		<tr>
	        <td colspan="4" style="text-align: right;">GRAND TOTAL:</td>
	        <td><i class="fa fa-inr"></i><span class="grandTotal pull-right"></span></td>
      </tr>
	
	</tbody>
</table>
</div>

app/views/customers/new.html.erb
<script>
  
  var cctvs = <%= Cctv.all.group_by{|x| [x.product.name, x.product_id].join(":") }.to_json.html_safe %>;
  var cctvsPrice = <%= Cctv.all.group_by{|x| [x.product.name, x.id].join(":") }.to_json.html_safe %>;


$(document).ready(function(){
  productValues();
  
});

</script>

<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<div >
  <table style="border:none">

<tr>
  <td><strong>NAME :</strong></td>
 <td><%= @customer.name %><a class="btn btn-dark btn-sm pull-right" id="invoice_button" data-toggle="modal" data-target="#invoice_modal">PREVIEW</a></td>
</tr>

<tr>
  <td><strong>CONTACT :</strong></td>
  <td><%= @customer.contact %></td>
</tr>

<tr>
  <td><strong>EMAIL :</strong></td>
  <td><%= @customer.email %></td>
</tr>

<tr>
  <td><strong>ADDRESS :</strong></td>
  <td><%= @customer.address %></td>
</tr>
</table>
</div>
</br>
<table>
  <thead>
  <tr>
    <th>ITEMS NAME</th>
    <th>CATEGORY</th>
    <th>PRICE</th>
    <th>QUANTITY</th>
    <th>TOTAL</th>
  </tr>
  </thead>

  <tbody>
 
  <% grandTotal = 0 %>
  <% @items.each do |item| %>
   
    <tr>  
      <td><%= item.product_name %></td>
      <td ><%= item.cctv.category %></td>
      <td style="width:150px;text-align: right;"><i class="fa fa-inr">&nbsp</i><%= item.price %></td>
      <td style="width:80px;text-align: center;"><%= item.quantity %></td>
      <% total = item.price.to_i * item.quantity.to_i %>
      <td style="width:220px;text-align: right;"><i class="fa fa-inr">&nbsp</i><%= total %>.00</td>
    </tr>
    <% grandTotal += total %>
    <% end %>
   
   <tr>
   <td colspan="4"></td>
   <td style="text-align: right;">GRAND TOTAL: <i class="fa fa-inr">&nbsp</i><%= grandTotal %>.00</td>
   </tr>
  
  </tbody>
</table>


<div class="modal fade" id="invoice_modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="container" id="print-me">
        <div class="row">
          <div class="col-md-12 model-print-logo">
            <center class="image">
              <%= image_tag('logo_2.png') %>
            </center>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12" style="font-size: 17px; color: white">
            <div class="text-center">
              <strong>Address: F-82-1st Floor, Raiser Plaza, Indira Market, Jaipur. Contact: 9799974142, 9680825595</strong>
            </div>
          </div>
        </div>
        <%= render 'customerPrint' %>
      </div>
      <div class="modal-footer">
        <button class="btn btn-primary" onclick="printDiv('print-me')">PRINT</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CCTV SERVER</title>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', media: 'all' %>

    
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      
      <%= yield %>
 
    </div>
  </body>
</html>